sudo: false
os: osx
language: node_js
cache:
  bundler: true
  directories:
    - node_modules
notifications:
  flowdock: e7454f5285e7b9ab67009802d5560490
node_js:
  - '0.10'
before_install:
  - brew update
