#!/bin/sh

mkdir travis-cache
if [ ! -f homebrew-cache.tar.gz ]; then
  tar czf homebrew-cache/travis-cache.tar.gz --directory /usr/local/Cellar wine libtool little-cms2 libtiff libicns freetype jpeg libgphoto2
fi
